 target 'Cal-Hacks-TBD' do
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleMaps'
  pod 'Stripe'
  pod 'Alamofire', '~> 4.7'
  use_frameworks!

   inherit! :search_paths    
   target 'Cal-Hacks-TBDTests' do
     inherit! :search_paths
     # Pods for testing
   end
 
   target 'Cal-Hacks-TBDUITests' do
     inherit! :search_paths
     # Pods for testing
   end
 
 
 end
